default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Format code

  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.12.1
  #   hooks:
  #     - id: blacken-docs
  #       args: [--line-length=120]
  #       additional_dependencies: [black==21.12b0]

  # - repo: https://github.com/charliermarsh/ruff-pre-commit
    # rev: "v0.0.237"
    # hooks:
    #   - id: ruff
    #     args: ["--fix"]
